//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : AuthFactory.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.login;


/** */
public class AuthFactory {
	/** */
	public boolean login(String userName, String passowrd) {
		return false;
	
	}
	
	/** */
	public boolean isAuthenticated() {
		return false;
	
	}
	
	/** */
	public boolean logout() {
		return false;
	
	}
}
