//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : ParticipantService.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.service;


/** */
public interface ParticipantService {
	/** */
	public boolean addNewParticipantFeedback(com.cg.fms.dto.Feedback feedback);
}
