//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : TrainingCoordinatorServiceImpl.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.service;

import java.util.List;

import com.cg.fms.dto.Feedback;
import com.cg.fms.dto.TrainingProgram;


/** */
public class TrainingCoordinatorServiceImpl implements TrainingCoordinatorService {
	/** */
	public List<TrainingProgram> getAllTrainingProgramList() {
		return null;
	}
	
	/** */
	public List<String> getEmployeeNames() {
		return null;
	}
	
	/** */
	public List<String> getCourseNames() {
		return null;
	}
	
	/** */
	public boolean updateTrainingProgramWithId(int id) {
		return false;
	}
	
	/** */
	public List<Feedback> getAllParticipantFeedback() {
		return null;
	}
	
	/** */
	public void getAllFeedbackDefaulterParticipant() {
	}
	
	/** */
	public List<String> getAllTrainingProgramNames() {
		return null;
	}
	
	/** */
	public boolean addNewTrainingEnrollment(com.cg.fms.dto.TrainingParticipant Parameter1) {
		return false;
	}
}
