//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : TrainingAdminServiceImpl.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.service;

import java.util.List;

import com.cg.fms.dto.Course;
import com.cg.fms.dto.Employee;
import com.cg.fms.dto.FacultySkill;
import com.cg.fms.dto.Feedback;
import com.cg.fms.dto.TrainingProgram;


/** */
public class TrainingAdminServiceImpl implements TrainingAdminService {
	/** */
	public List<Feedback> getAllParticipantFeedback() {
		return null;
	}
	
	/** */
	public void getAllFeedbackDefaulterParticipant() {
	}
	
	/** */
	public List<FacultySkill> getAllFacultyList() {
		return null;
	}
	
	/** */
	public List<Course> getAllCourseList() {
		return null;
	}
	
	/** */
	public boolean updateCourseWithId(int id) {
		return false;
	}
	
	/** */
	public List<Employee> getAllEmployeeList() {
		return null;
	}
	
	/** */
	public List<TrainingProgram> getAllTrainingProgramList() {
		return null;
	}
}
