//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : TrainingCoordinatorService.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.service;

import java.util.List;

import com.cg.fms.dto.Feedback;
import com.cg.fms.dto.TrainingProgram;


/** */
public interface TrainingCoordinatorService {
	/** */
	public List<TrainingProgram> getAllTrainingProgramList();
	
	/** */
	public List<String> getEmployeeNames();
	
	/** */
	public List<String> getCourseNames();
	
	/** */
	public boolean updateTrainingProgramWithId(int id);
	
	/** */
	public List<Feedback> getAllParticipantFeedback();
	
	/** */
	public void getAllFeedbackDefaulterParticipant();
	
	/** */
	public List<String> getAllTrainingProgramNames();
	
	/** */
	public boolean addNewTrainingEnrollment(com.cg.fms.dto.TrainingParticipant Parameter1);
}
