//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : TrainingAdminService.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.service;

import java.util.List;
import com.cg.fms.dto.Feedback;
import com.cg.fms.dto.Employee;
import com.cg.fms.dto.Course;
import com.cg.fms.dto.FacultySkill;
import com.cg.fms.dto.TrainingProgram;


/** */
public interface TrainingAdminService {
	/** */
	public List<Feedback> getAllParticipantFeedback();
	
	/** */
	public void getAllFeedbackDefaulterParticipant();
	
	/** */
	public List<FacultySkill> getAllFacultyList();
	
	/** */
	public List<Course> getAllCourseList();
	
	/** */
	public boolean updateCourseWithId(int id);
	
	/** */
	public List<Employee> getAllEmployeeList();
	
	/** */
	public List<TrainingProgram> getAllTrainingProgramList();
}
