//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : Course.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.dto;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/** */
public class Course {
	/** */
	private int id;
	
	/** */
	private String name;
	
	/** */
	private int duration;
	
	private List<Integer> faculty = null;

	private List<String> facultyNames = null;
	

	

	public List<String> getFacultyNames() {
		return facultyNames;
	}


	public void setFacultyNames(List<String> facultyNames) {
		this.facultyNames = facultyNames;
	}


	public int getId() {
		return id;
	}


	public String getName() {
		return name;
	}


	public int getDuration() {
		return duration;
	}


	public List<Integer> getFaculty() {
		return faculty;
	}


	public void setId(int id) {
		this.id = id;
	}


	public void setName(String name) {
		this.name = name;
	}


	public void setDuration(int duration) {
		this.duration = duration;
	}


	public void setFaculty(List<Integer> faculty) {
		this.faculty = faculty;
	}


	public Course(int id, String name, int duration, List<Integer> faculty,List<String> facultyNames) {
		super();
		this.id = id;
		this.name = name;
		this.duration = duration;
		this.faculty = faculty;
		this.facultyNames = facultyNames;
	}


	public Course() {
		faculty = new ArrayList<Integer>();
		facultyNames = new ArrayList<String>();
	}


	@Override
	public String toString() {
		return "Course [id=" + id + ", name=" + name + ", duration=" + duration
				+ ", faculty=" + faculty + ", facultyNames=" + facultyNames
				+ "]";
	}

}
