//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : Employee.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.dto;


/** */
public class Employee {
	/** */
	private int id;
	
	/** */
	private String name;
	
	/** */
	private String password;
	
	/** */
	private String role;
	
	/** */
	public void Employee() {
	
	}
}
