//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : FacultySkill.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.dto;


/** */
public class FacultySkill {
	/** */
	private int id;
	
	/** */
	private String[] skillSet;
	
	/** */
	public Object name;
	
	/** */
	public void FacultySkill() {
	
	}
}
