//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : Feedback.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.dto;

import java.time.LocalDate;


/** */
public class Feedback {
	/** */
	private int participantId;
	
	/** */
	private int trainingCode;
	
	/** */
	private String comment;
	
	/** */
	private String suggestions;
	
	/** */
	private int FbPrsComm;
	
	/** */
	private int FbClrfyDbts;
	
	/** */
	private int FbTm;
	
	/** */
	private int FbHandout;
	
	/** */
	private int FBHwSwNtwrk;
	
	/** */
	private String participantName;
	
	/** */
	private LocalDate feedbackDate;
	
	/** */
	public void Feedback() {
	
	}
}
