//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : TrainingParticipant.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.dto;


/** */
public class TrainingParticipant {
	/** */
	private int trainingCode;
	
	/** */
	private int employeeId;
	
	/** */
	public void TrainingParticipant() {
	
	}

	public int getTrainingCode() {
		return trainingCode;
	}

	public void setTrainingCode(int trainingCode) {
		this.trainingCode = trainingCode;
	}

	public int getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public TrainingParticipant(int trainingCode, int employeeId) {
		super();
		this.trainingCode = trainingCode;
		this.employeeId = employeeId;
	}

	@Override
	public String toString() {
		return "TrainingParticipant [trainingCode=" + trainingCode
				+ ", employeeId=" + employeeId + "]";
	}
	
	
	
}
