//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : TrainingParticipant.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.dto;


/** */
public class TrainingParticipant {
	/** */
	private int trainingCode;
	
	/** */
	private int employeeId;
	
	/** */
	public void TrainingParticipant() {
	
	}
}
