//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : TrainingProgram.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.dto;

import java.time.LocalDate;


/** */
public class TrainingProgram {
	/** */
	private int trainingCode;
	
	/** */
	private int facultyCode;
	
	/** */
	private int courseCode;
	
	/** */
	private LocalDate startDate;
	
	/** */
	private LocalDate endDate;
	
	/** */
	private String trainingName;
	
	/** */
	public void TrainingProgram() {
	
	}
}
