//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : FeedbackSysException.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.exception;


/** */
public class FeedbackSysException extends Exception{

	public FeedbackSysException() {
		super();
		// TODO Auto-generated constructor stub
	}

	public FeedbackSysException(String message, Throwable cause,
			boolean enableSuppression, boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
		// TODO Auto-generated constructor stub
	}

	public FeedbackSysException(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

	public FeedbackSysException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}

	public FeedbackSysException(Throwable cause) {
		super(cause);
		// TODO Auto-generated constructor stub
	}
	
	
	
}
