//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : FMSDaoImpl.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.dao;

import java.util.List;

import com.cg.fms.dto.Course;
import com.cg.fms.dto.Employee;
import com.cg.fms.dto.FacultySkill;
import com.cg.fms.dto.Feedback;
import com.cg.fms.dto.TrainingParticipant;
import com.cg.fms.dto.TrainingProgram;


/** */
public class FMSDaoImpl implements FMSDao {

	@Override
	public List<TrainingProgram> getAllTrainingProgramList() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean updateTrainingProgramWithId(int id) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public List<String> getAllTrainingProgramNames() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void addNewTrainingProgram(TrainingProgram trainneEnrollment) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List<FacultySkill> getAllFacultyList() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Course> getAllCourseList() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean updateCourseWithId(int id) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public List<String> getCourseNames() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Employee> getAllEmployeeList() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<String> getEmployeeNames() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Feedback> getAllfeedbackList() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean addNewFeedback(Feedback feedback) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean addNewParticipantTrainingEnroll(
			TrainingParticipant Parameter1) {
		// TODO Auto-generated method stub
		return false;
	}
	
}
