//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : feedbackFactory.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.util;

import java.time.LocalDate;
import java.util.List;

import com.cg.fms.dto.Feedback;


/** */
public class feedbackFactory {
	/** */
	public List<Feedback> generateTrainingFeedbackReport(LocalDate date, List<Feedback> feedbackList) {
		return feedbackList;
	
	}
	
	/** */
	public List<Feedback> generateFacultyFeedbackReport(LocalDate date, List<Feedback> feedbackList) {
		return feedbackList;
	
	}
}
