//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedback Management System
//  @ File Name : Utility.java
//  @ Date : 15-09-2017
//  @ Author : Vikas Chaudhary
//
//



package com.cg.fms.util;


/** */
public class Utility {
	/** */
	public void getfacultyListWithNames() {
	
	}
}
